filetype plugin indent on	        " turn on filetype recognition
syntax on 			        " syntax highlighting
set history=2500                        " 2500 buffer
set backspace=start,eol,indent	        " set where backspace will function
set hidden				" allow buffers to be stored in the background so you can switch to different screens 
set noswapfile    			" disable swp files
set incsearch			      	" search as you type
set showmatch                           " match parens
set hls			                " highlight searches
set nu                                  " show numbered lines
set ruler                               " show position at the bottom right
set path=.,**                           " set paths to include current file and folder and subdirectories
set mouse=a				" allow mouse interaction
set clipboard=unnamed		  	" allow saving to system clipboard

let $RTP=split(&runtimepath, ',')[0]	" list of paths for vim xcmds
let $RC="$HOME/.vim/vimrc"






call plug#begin('~/.vim/plugged')
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Highlight yanked text
Plug 'machakann/vim-highlightedyank'

" Marker manager
Plug 'kshenoy/vim-signature'

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Initialize plugin system
" - Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()
" You can revert the settings after the call like so:
"   filetype indent off   " Disable file-type-specific indentation
"   syntax off            " Disable syntax highlighting
